sudo: required
dist: trusty
language: node_js

node_js:
  - "6.10.2"

script:
  - npm test
  - npm run e2e

# for unit tests
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    # required by node-gyp to build some packages
    packages:
    - g++-4.8
    - google-chrome-stable
